services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data: /var
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    container_name: txFilter
    depends_on:
      - postgres
    env_file:
      - ../.env
    ports:
      - "8080:8080"

volumes:
  postgres_data:
